# Generated by Django 5.2.14 on 2026-06-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apikey_organisation_and_alter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
    ]
