# Generated by Django 5.2.14 on 2026-08-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_finance',
            field=models.BooleanField(default=False, help_text='Grants access to the Xero integration. Only takes effect for staff (admin/associate).'),
        ),
    ]
