# Generated by Django 5.2.14 on 2026-06-03 14:28

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The everyday name staff use to find this org.', max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='Registered Companies House name (used on contracts and credit checks).', max_length=255)),
                ('trading_name', models.CharField(blank=True, help_text='“Trading as” name, when different from the legal name.', max_length=255)),
                ('companies_house_number', models.CharField(blank=True, db_index=True, help_text='UK CH number — 8 digits, or NI/SC/OC + 6 digits (LLPs).', max_length=10, verbose_name='Companies House number')),
                ('address_line1', models.CharField(blank=True, help_text='House number and street', max_length=255, verbose_name='Line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Flat, suite, etc. (optional)', max_length=255, verbose_name='Line 2')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address_county', models.CharField(blank=True, help_text='Optional', max_length=100, verbose_name='County')),
                ('address_postcode', models.CharField(blank=True, max_length=10, verbose_name='Postcode')),
                ('hubspot_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('home_address_line1', models.CharField(blank=True, help_text='House number and street', max_length=255, verbose_name='Line 1')),
                ('home_address_line2', models.CharField(blank=True, help_text='Flat, etc. (optional)', max_length=255, verbose_name='Line 2')),
                ('home_address_city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('home_address_county', models.CharField(blank=True, help_text='Optional', max_length=100, verbose_name='County')),
                ('home_address_postcode', models.CharField(blank=True, max_length=10, verbose_name='Postcode')),
                ('hubspot_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to=settings.AUTH_USER_MODEL)),
                ('organisations', models.ManyToManyField(blank=True, help_text='A contact can belong to more than one organisation.', related_name='contacts', to='crm.organisation')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('flat_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('document_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hubspot_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('co_applicants', models.ManyToManyField(blank=True, related_name='co_applicant_deals', to='crm.contact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.contact')),
                ('introducer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_deals', to='crm.contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, help_text="The organisation this deal is for. May be different from any of the customer's organisations; can be set later.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Bank statements, Photo ID, Accounts', max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('provided', 'Provided')], default='requested', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to=crm.models.document_upload_path)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.deal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-required', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='crm.deal')),
                ('organisation', models.ForeignKey(blank=True, help_text='The supplier this amount goes to. Optional — may be added later.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='crm.organisation')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apr', models.DecimalField(decimal_places=2, help_text='e.g. 5.99 for 5.99%.', max_digits=5)),
                ('term', models.PositiveSmallIntegerField(help_text='Term in months.')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from deal funded amount, APR and term.', max_digits=12, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm.deal')),
            ],
            options={
                'ordering': ['deal', 'term'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='selected_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.quote'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('application', 'Application'), ('info_received', 'Info Received')], max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='crm.deal')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
    ]
