# Generated by Django 5.2.14 on 2026-06-04 06:52

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='description',
            field=models.TextField(blank=True, help_text='What this participation covers (e.g. equipment, install fees).'),
        ),
        migrations.AddField(
            model_name='participation',
            name='invoice',
            field=models.FileField(blank=True, help_text="The supplier's invoice (PDF).", null=True, upload_to=crm.models.participation_invoice_upload_path),
        ),
        migrations.AddField(
            model_name='participation',
            name='invoice_contact',
            field=models.ForeignKey(blank=True, help_text='The supplier-side contact who handles invoicing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_participations', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='participation',
            name='invoice_number',
            field=models.CharField(blank=True, help_text="Supplier's invoice / reference number for this amount.", max_length=100),
        ),
    ]
