# Generated by Django 5.2.14 on 2026-05-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='document_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='equipment_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_deals', to='crm.organisation'),
        ),
        migrations.AddField(
            model_name='deal',
            name='flat_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='funded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='introducer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_deals', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apr', models.DecimalField(decimal_places=2, help_text='Annual percentage rate, e.g. 5.99 for 5.99%.', max_digits=5)),
                ('term', models.PositiveSmallIntegerField(help_text='Term in months.')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm.deal')),
            ],
            options={
                'ordering': ['deal', 'term'],
            },
        ),
    ]
