# Generated by Django 5.2.14 on 2026-06-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_participation_invoice_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_number', models.CharField(blank=True, help_text="The lender's reference for this proposal.", max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=16)),
                ('contact', models.ForeignKey(blank=True, help_text='The contact at the lender, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.contact')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.deal')),
                ('lender', models.ForeignKey(help_text='The lender we sent this proposal to.', on_delete=django.db.models.deletion.PROTECT, related_name='lender_proposals', to='crm.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
