# Generated by Django 5.2.14 on 2026-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_deal_commission_deal_document_fee_deal_earnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from deal funded amount, APR and term.', max_digits=12, null=True),
        ),
    ]
