# Generated by Django 5.2.14 on 2026-06-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_participation_invoice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='home_address_line2',
            field=models.CharField(blank=True, help_text='Flat, etc.', max_length=255, verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Flat, suite, etc.', max_length=255, verbose_name='Line 2'),
        ),
    ]
