# Generated by Django 5.2.14 on 2026-05-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_backfill_initial_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='co_applicants',
            field=models.ManyToManyField(blank=True, related_name='co_applicant_deals', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='selected_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.quote'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='apr',
            field=models.DecimalField(decimal_places=2, help_text='e.g. 5.99 for 5.99%.', max_digits=5),
        ),
    ]
