# Generated by Django 5.2.14 on 2026-05-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_contact_date_of_birth_contact_home_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='home_address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_address_county',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_address_line1',
            field=models.CharField(blank=True, help_text='House number and street', max_length=255, verbose_name='Line 1'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_address_line2',
            field=models.CharField(blank=True, help_text='Flat, etc. (optional)', max_length=255, verbose_name='Line 2'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_address_postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_county',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_line1',
            field=models.CharField(blank=True, help_text='House number and street', max_length=255, verbose_name='Line 1'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Flat, suite, etc. (optional)', max_length=255, verbose_name='Line 2'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Postcode'),
        ),
    ]
