# Generated by Django 5.2.14 on 2026-06-08 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_xero'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_months', models.PositiveSmallIntegerField(help_text='Term in months, e.g. 60.')),
                ('yield_percent', models.DecimalField(decimal_places=2, help_text='Annual yield, e.g. 15.65 for 15.65%.', max_digits=5, verbose_name='Yield')),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Smallest loan this band applies to, e.g. 1000.', max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Largest loan this band applies to, e.g. 250000.', max_digits=12)),
                ('rate_per_thousand', models.DecimalField(decimal_places=2, help_text='Rate per £1,000 of capital.', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to withdraw this band without deleting it.')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, help_text='Date this rate took effect. On overlap, the latest active band wins.')),
                ('organisation', models.ForeignKey(help_text='The lender this rate belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rate_bands', to='crm.organisation')),
            ],
            options={
                'ordering': ['organisation', 'term_months', 'min_amount'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_amount__gte', models.F('min_amount'))), name='rateband_max_gte_min')],
            },
        ),
    ]
