# Generated by Django 5.2.14 on 2026-05-23 08:52

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_contact_home_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Bank statements, Photo ID, Accounts', max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('provided', 'Provided')], default='requested', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to=crm.models.document_upload_path)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.deal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-required', 'name'],
            },
        ),
    ]
