# Generated by Django 5.2.14 on 2026-06-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rateband'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateband',
            name='rate_per_thousand',
        ),
    ]
