# Generated by Django 5.2.14 on 2026-06-03 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Optional at creation — may be set later (e.g. by the customer via the portal).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='crm.organisation'),
        ),
    ]
