# Generated by Django 5.2.14 on 2026-06-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rateband_drop_rpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateband',
            name='max_amount',
            field=models.PositiveIntegerField(help_text='Largest loan this band applies to, e.g. 250000.'),
        ),
        migrations.AlterField(
            model_name='rateband',
            name='min_amount',
            field=models.PositiveIntegerField(help_text='Smallest loan this band applies to, e.g. 1000.'),
        ),
    ]
