# Generated by Django 5.2.14 on 2026-06-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_rateband_integer_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional. Added to the advance — the customer's monthly payment is calculated on the grossed-up amount.", max_digits=5, null=True, verbose_name='Commission %'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from deal funded amount, APR, term and commission.', max_digits=12, null=True),
        ),
    ]
