# Generated by Django 5.2.14 on 2026-06-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_deal_funded_amount_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='equipment_supplier',
        ),
    ]
