# Generated by Django 5.2.14 on 2026-06-08 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_quote_commission_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='apr',
        ),
        migrations.AddField(
            model_name='quote',
            name='rate',
            field=models.ForeignKey(help_text='The lender rate band this quote is priced on.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='crm.rateband'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from deal funded amount, rate, term and commission.', max_digits=12, null=True),
        ),
    ]
