# Generated by Django 5.2.14 on 2026-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_contact_orgs_m2m_and_deal_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='companies_house_number',
            field=models.CharField(blank=True, db_index=True, help_text='UK CH number — 8 digits, or NI/SC/OC + 6 digits (LLPs).', max_length=10, verbose_name='Companies House number'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered Companies House name (used on contracts and credit checks).', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='trading_name',
            field=models.CharField(blank=True, help_text='“Trading as” name, when different from the legal name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(help_text='The everyday name staff use to find this org.', max_length=255),
        ),
    ]
