# Generated by Django 5.2.14 on 2026-06-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_quote_rate_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='monthly_payment',
        ),
    ]
