# Generated by Django 5.2.14 on 2026-06-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_quote_monthly_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='introducer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_deals', to='crm.organisation'),
        ),
    ]
