# Generated by Django 5.2.14 on 2026-06-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sitesettings'),
        ('crm', '0017_deal_selected_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='created_via_api_key',
            field=models.ForeignKey(blank=True, help_text='The partner API key that POSTed this deal in, if any. Used to attribute and rate-limit API-created deals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to='accounts.apikey'),
        ),
    ]
