# Generated by Django 5.2.14 on 2026-07-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_deal_created_via_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, help_text='Honorific (Dr, Prof, Mrs …). Optional.', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='first_payment_date',
            field=models.DateField(blank=True, help_text='Date the first repayment falls due.', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='repayment_profile',
            field=models.CharField(blank=True, help_text='Free-text repayment profile (e.g. monthly, quarterly, balloon). May be structured later.', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, help_text='Shared / role inbox for the organisation (e.g. info@, reception@). Contacts may share this address.', max_length=254),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, help_text='Main phone number for the organisation.', max_length=32),
        ),
        migrations.AddField(
            model_name='organisation',
            name='url',
            field=models.URLField(blank=True, help_text='Homepage / website URL.', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Nullable — some commercial / historical deals genuinely have no individual customer, only an organisation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('application', 'Application'), ('info_received', 'Info Received'), ('proposal_submitted', 'Proposal Submitted'), ('proposal_approved', 'Proposal Approved'), ('documents_out', 'Documents Out'), ('awaiting_payout', 'Awaiting Payout'), ('deal_live', 'Deal Live'), ('commission_invoice_requested', 'Commission Invoice Requested'), ('invoice_requested', 'Invoice Requested'), ('invoice_received', 'Invoice Received'), ('proposal_declined', 'Proposal Declined'), ('proposal_withdrawn', 'Proposal Withdrawn')], max_length=32),
        ),
    ]
