# Generated by Django 5.2.14 on 2026-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('hubspot_note', 'HubSpot note'), ('hubspot_email', 'HubSpot email'), ('hubspot_migration_comment', 'HubSpot migration comment'), ('admin_comment', 'Admin comment')], max_length=32),
        ),
    ]
