# Generated by Django 5.2.14 on 2026-08-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_move_deposit_balloon_profile_to_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='mf_invoice_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('application', 'Application'), ('info_received', 'Info Received'), ('proposal_submitted', 'Proposal Submitted'), ('proposal_approved', 'Proposal Approved'), ('proposal_declined', 'Proposal Declined'), ('documents_out', 'Documents Out'), ('supplier_invoice_requested', 'Supplier Invoice Requested'), ('supplier_invoice_received', 'Supplier Invoice Received'), ('mf_invoiced', 'MF Invoiced'), ('deal_live', 'Deal Live'), ('dormant', 'Dormant'), ('lost', 'Lost'), ('settled', 'Settled')], max_length=32),
        ),
    ]
