# Generated by Django 5.2.14 on 2026-08-04 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_deal_mf_invoice_number_alter_stage_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['deal', '-datetime'], name='crm_note_deal_datetime'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['deal', '-occurred_at'], name='crm_stage_deal_occurred'),
        ),
    ]
