# Generated by Django 5.2.14 on 2026-08-05 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_note_crm_note_deal_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="Staff member responsible for this contact — not the contact's own portal login (that's `user`).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this organisation. Optional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
