# Generated by Django 5.2.14 on 2026-08-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_contact_owner_organisation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='sector',
            field=models.CharField(blank=True, choices=[('dental', 'Dental'), ('dental_lab', 'Dental Lab'), ('doctors', 'Doctors'), ('pharmacy', 'Pharmacy'), ('veterinary', 'Veterinary'), ('physio_chiro', 'Physio/Chiro'), ('cosmetic', 'Cosmetic'), ('optical', 'Optical'), ('hearing', 'Hearing'), ('hair_clinic', 'Hair Clinic'), ('education', 'Education'), ('non_healthcare', 'Non-healthcare profession'), ('other', 'Other')], help_text='The profession/sector this organisation operates in. Optional.', max_length=32, null=True),
        ),
    ]
