# Generated by Django 5.2.14 on 2026-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_organisation_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='type',
            field=models.CharField(blank=True, choices=[('asset_finance', 'Asset Finance'), ('commercial_finance', 'Commercial Finance')], help_text='The kind of finance this deal is for. Optional.', max_length=32, null=True),
        ),
    ]
