# Generated by Django 5.2.14 on 2026-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='term_end_date',
            field=models.DateField(blank=True, help_text="When the finance term ends. Migrated from HubSpot for historical deals; leave blank to derive it from the first payment date + selected quote's term.", null=True),
        ),
    ]
