# Generated by Django 5.2.14 on 2026-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_deal_term_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='type',
            field=models.CharField(blank=True, choices=[('asset_finance', 'Asset Finance'), ('commercial_finance', 'Commercial Finance'), ('business_loans', 'Business Loans'), ('structured_finance', 'Structured Finance'), ('kmc_associates', 'KMC Associates'), ('short_term_finance', 'Short Term Finance')], help_text='The kind of finance this deal is for. Optional.', max_length=32, null=True),
        ),
    ]
