# Generated by Django 5.2.14 on 2026-08-10 09:05

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_deal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_id', models.PositiveIntegerField()),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('submission_id', models.PositiveIntegerField(unique=True)),
                ('submitter_id', models.PositiveIntegerField(blank=True, null=True)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('completed', 'Completed'), ('declined', 'Declined'), ('voided', 'Voided')], default='sent', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.CharField(blank=True, max_length=512)),
                ('audit_log_file', models.FileField(blank=True, null=True, upload_to=crm.models.signature_audit_upload_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='crm.document')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
