# Generated by Django 5.2.14 on 2026-08-20 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_signaturerequest_deal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='companies_house_number',
            field=models.CharField(blank=True, db_index=True, help_text='8 digits, or NI/SC/OC + 6 digits (LLPs)', max_length=10, verbose_name='Companies House number'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, help_text='Shared / role inbox for the organisation', max_length=254),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered Companies House name', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(help_text='The everyday name staff use to find this org', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this organisation. Optional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, help_text='Main number for the organisation', max_length=32),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='sector',
            field=models.CharField(blank=True, choices=[('dental', 'Dental'), ('dental_lab', 'Dental Lab'), ('doctors', 'Doctors'), ('pharmacy', 'Pharmacy'), ('veterinary', 'Veterinary'), ('physio_chiro', 'Physio/Chiro'), ('cosmetic', 'Cosmetic'), ('optical', 'Optical'), ('hearing', 'Hearing'), ('hair_clinic', 'Hair Clinic'), ('education', 'Education'), ('non_healthcare', 'Non-healthcare profession'), ('other', 'Other')], help_text='The sector of operation. Optional', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='trading_name',
            field=models.CharField(blank=True, help_text='When different', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='url',
            field=models.URLField(blank=True, help_text='Homepage / website URL', max_length=255),
        ),
    ]
