# Generated by Django 5.2.14 on 2026-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_proposal_notified_at_alter_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='source',
            field=models.CharField(blank=True, choices=[('introducer', 'Introducer'), ('existing_customer', 'Existing Customer'), ('supplier', 'Supplier'), ('referral', 'Referral'), ('exhibition', 'Exhibition'), ('meeting', 'Meeting'), ('website', 'Website'), ('search_engine', 'Search Engine'), ('campaign_advert', 'Campaign / Advert'), ('e_shot', 'E-shot'), ('twitter', 'Twitter'), ('other', 'Other')], help_text='How this deal came to MediFinance. Optional.', max_length=32, null=True),
        ),
    ]
