# Generated by Django 5.2.14 on 2026-09-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_deal_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('initial_contact', 'Initial Contact'), ('application', 'Application'), ('info_received', 'Info Received'), ('quoting', 'Quoting'), ('proposal_submitted', 'Proposal Submitted'), ('proposal_approved', 'Proposal Approved'), ('proposal_declined', 'Proposal Declined'), ('client_notified', 'Client Notified'), ('documents_out', 'Documents Out'), ('legals', 'Legals'), ('supplier_invoice_requested', 'Supplier Invoice Requested'), ('supplier_invoice_received', 'Supplier Invoice Received'), ('mf_invoiced', 'MF Invoiced'), ('deal_live', 'Deal Live'), ('dormant', 'Dormant'), ('lost', 'Lost'), ('settled', 'Settled')], max_length=32),
        ),
    ]
