# Generated by Django 5.2.14 on 2026-09-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_alter_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='type',
            field=models.CharField(blank=True, choices=[('asset_finance', 'Asset Finance'), ('commercial_finance', 'Commercial Finance'), ('business_loans', 'Business Loans'), ('structured_finance', 'Structured Finance'), ('kmc_associates', 'KMC Associates'), ('short_term_finance', 'Short Term Finance'), ('practice_purchase', 'Practice Purchase'), ('refinance', 'Refinance'), ('renovation', 'Renovation'), ('startup', 'Startup'), ('property_purchase', 'Property Purchase'), ('bridging_loan', 'Bridging Loan')], help_text='The kind of finance this deal is for. Optional.', max_length=32, null=True),
        ),
    ]
