# Generated by Django 5.2.14 on 2026-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_alter_deal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('hubspot_note', 'HubSpot note'), ('hubspot_email', 'HubSpot email'), ('hubspot_migration_comment', 'HubSpot migration comment'), ('admin_comment', 'Admin comment'), ('customer_update', 'Customer update')], max_length=32),
        ),
    ]
