# Generated by Django 5.2.14 on 2026-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_alter_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerequest',
            name='signing_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
