# Generated by Django 5.2.14 on 2026-09-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_signaturerequest_signing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='flat_fee',
        ),
        migrations.AddField(
            model_name='deal',
            name='final_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='initial_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='non_completion_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Charged as a percentage if the deal doesn't complete.", max_digits=5, null=True, verbose_name='Non-completion fee %'),
        ),
    ]
